Laboratorio1/Laboratorio1/Models/Jugador.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Laboratorio1.Models
{
    public class Jugador
    {
        public int JugadorID { get; set; }
        public string Apellido { get; set; }
        public string Nombre { get; set; }
        public string Club { get; set; }
        public string Posicion { get; set; }
        public int Salario { get; set; }
    }
}

Laboratorio1/Laboratorio1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Laboratorio1.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Laboratorio1/Laboratorio1/Controllers/JugadorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Laboratorio1.DBContext;
using System.Net;
using System.IO;
using Laboratorio1.Models;
using System.Timers;
using Laboratorio1.LOG;

namespace Laboratorio1.Controllers
{
    public class JugadorController : Controller
    { 
        public DefaultConnection db = DefaultConnection.getInstance;

        // GET: Jugador
        public ActionResult Index()
        {
            
            return View(db.Jugadores.ToList());
        }

        // GET: Jugador/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Jugador/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Jugador/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include ="Nombre,Apellido,Club,Posicion,Salario")]Models.Jugador jugador)
        {
            LogFile timing = new LogFile();
            timing.StartTimer();
             
            if (ModelState.IsValid)
            {
                jugador.JugadorID = ++db.IdActual;
                db.Jugadores.Add(jugador);

                timing.Logcreate("Crear");
                return RedirectToAction("Index");
            }
            
            return View(jugador);
        }

        // GET: Jugador/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Models.Jugador jugador = db.Jugadores.Find(x => x.JugadorID == id);
            if (jugador == null)
            {
                
                return HttpNotFound();
            }

            return View(jugador);
        }

        // POST: Jugador/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "JugadorID, Apellido, Nombre, Club, Posicion, Salario")]Models.Jugador jugador)
        {
            LogFile timing = new LogFile();
            timing.StartTimer();
            if (ModelState.IsValid)
            {
                Models.Jugador modifiedJugador = db.Jugadores.Find(x => x.JugadorID == jugador.JugadorID);

                if (modifiedJugador == null)
                {
                    timing.Logcreate("Editar");
                    return HttpNotFound();
                }

                modifiedJugador.Club = jugador.Club;
                modifiedJugador.Salario = jugador.Salario;
                timing.Logcreate("Editar");
                return View(modifiedJugador);
            }
            timing.Logcreate("Editar");
            return RedirectToAction("Index");
        }
        
        // GET: Jugador/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Models.Jugador jugador = db.Jugadores.Find(x => x.JugadorID == id);

            if (jugador == null)
            {
                return HttpNotFound();
            }
            return View(jugador);
        }
        

        // POST: Jugador/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            LogFile timing = new LogFile();
            timing.StartTimer();
            db.Jugadores.Remove(db.Jugadores.Find(x => x.JugadorID == id));
            timing.Logcreate("Eliminar");
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult UploadFile()
        {
            return View();
        }
        [HttpPost]
       [ValidateAntiForgeryToken]
        public ActionResult UploadFile(HttpPostedFileBase File)
            
        {
            LogFile timing = new LogFile();
           
            string filePath = string.Empty;
            if (File != null)
            {
                string path = Server.MapPath("~/UploadedFiles/");
                filePath = path + Path.GetFileName(File.FileName);
                string extension = Path.GetExtension(File.FileName);
                File.SaveAs(filePath);
                ViewBag.Message = "Archivo Cargado";

                string csvDatos = System.IO.File.ReadAllText(filePath);
                string[] csvDatos_ = csvDatos.Split('\n');
                
                foreach (string fila in csvDatos_)
                {

                    if (!string.IsNullOrEmpty(fila)&& fila !=csvDatos_[0])
                    {
                        db.Jugadores.Add(new Models.Jugador
                        {
                            JugadorID = ++db.IdActual,
                            Club = fila.Split(',')[0],
                            Apellido = fila.Split(',')[1],
                            Nombre = fila.Split(',')[2],
                            Posicion = fila.Split(',')[3],
                            Salario = (int)Convert.ToDouble(fila.Split(',')[4])
                        });
                    }
                }


                timing.Logcreate("Cargar Archivo");
                return RedirectToAction("Index");
            }

            timing.Logcreate("Cargar Archivo");
            return View();
           
        }
        [HttpGet]
        public ActionResult DeleteByfile()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult DeleteByfile(HttpPostedFileBase File)
       {
            LogFile timing = new LogFile();
            timing.StartTimer();
            var listdelete = new List<Jugador>();
            var filepath = string.Empty;

            if (File != null)
            {
                string path = Server.MapPath("~/Deleting/");
                filepath = path + Path.GetFileName(File.FileName);
                string extension = Path.GetExtension(File.FileName);
                File.SaveAs(filepath);
                ViewBag.Message = "Archivo Cargado";
                string csvDatos = System.IO.File.ReadAllText(filepath);
                string[] csvDatos_ = csvDatos.Split('\n');

                foreach (string fila in csvDatos_)
                {

                    if (!string.IsNullOrEmpty(fila) && fila != csvDatos_[0])
                    {
                        listdelete.Add(new Models.Jugador
                        {

                            Club = fila.Split(',')[0],
                            Apellido = fila.Split(',')[1],
                            Nombre = fila.Split(',')[2],
                            Posicion = fila.Split(',')[3],
                            Salario = (int)Convert.ToDouble(fila.Split(',')[4])
                        });
                    }
                }

                foreach (Jugador futbolista in listdelete)
                {
                    for(int i = 0; i< db.Jugadores.Count; i++)
                    {
                        Jugador toDelete = db.Jugadores[i];
                        if(toDelete.Nombre == futbolista.Nombre && toDelete.Apellido == futbolista.Apellido && toDelete.Club == futbolista.Club)
                        {
                            db.Jugadores.Remove(toDelete);
                        }

                    }


                }
               
            }
            timing.Logcreate("Eliminar por Archivo");
            return View();

        }
       
    }
}

Laboratorio1/Laboratorio1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>EBASE DE DATOS MAJOR LEAGUE SOCCER</h1>
    <p class="lead">JUGADORES MAJOR LEAGUE SOCCER</p>
    <p>Bienvenido a la Base de Datos de Jugadores de la Major League Soccer</p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Ver Jugadores</h2>
        <p>
        </p>
        <p><a class="btn btn-default" @Html.ActionLink("Añadir Manualmente", "Create", "Jugador")</a></p>

    </div>
    <div class="col-md-4">
        <h2>Cargar Archivo</h2>
        <p></p>
        <p><a class="btn btn-default"  @Html.ActionLink("Cargar Archivo","UploadFile","Jugador")</a></p>
    </div>
    
</div>

Laboratorio1/Laboratorio1/Views/Jugador/Create.cshtml
@model Laboratorio1.Models.Jugador

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Jugador</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Apellido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Club, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Club, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Club, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Posicion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Posicion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Posicion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Salario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Salario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Salario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Laboratorio1/Laboratorio1/Views/Jugador/Delete.cshtml
@model Laboratorio1.Models.Jugador

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>
<h3>¿Estas Seguro de Eliminar a Este jugador?</h3>
<div>
    <h4>Jugador</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apellido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Club)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Club)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Posicion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Posicion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Salario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Salario)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Laboratorio1/Laboratorio1/Views/Jugador/DeleteByfile.cshtml
@{
    ViewBag.Title = "DeleteByfile";
}

<h2>DeleteByfile</h2>
@using (Html.BeginForm("DeleteByfile",
                        "Jugador",
                        FormMethod.Post,
                        new { enctype = "multipart/form-data" }))

{
    @Html.AntiForgeryToken()
    <label for="file">Cargar Archivo:</label>
    <input type="file" name="file" id="file" /><br><br>
    <input type="submit" value="Cargar Archivo" />
    <br><br>
    @ViewBag.Message
}

Laboratorio1/Laboratorio1/Views/Jugador/Edit.cshtml
@model Laboratorio1.Models.Jugador

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Jugador</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.JugadorID)

        <div class="form-group">
            @Html.LabelFor(model => model.Apellido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Apellido, new { @disabled="disabled"})
                @Html.ValidationMessageFor(model => model.Apellido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Nombre, new { @disabled="disabled"})
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Club, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Club, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Club, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Posicion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Posicion, new { @disabled="disabled"})
                @Html.ValidationMessageFor(model => model.Posicion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Salario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Salario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Salario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Laboratorio1/Laboratorio1/Views/Jugador/Index.cshtml
@model IEnumerable<Laboratorio1.Models.Jugador>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Agregar jugador", "Create") |
    @Html.ActionLink("Eliminar con Archivo", "DeleteByfile")
   
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Apellido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Club)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Posicion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Salario)
        </th>
        <th></th>
    </tr>
    
@foreach (var item in Model) {
    if (Model == null)
    {

    }
    else
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Apellido)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Club)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Posicion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Salario)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id = item.JugadorID }) |
            @Html.ActionLink("Eliminar", "Delete", new { id = item.JugadorID })
        </td>
    </tr>
    }
}

</table>

Laboratorio1/Laboratorio1/Views/Jugador/UploadFile.cshtml
@{
    ViewBag.Title = "UploadFile";

}

<h2>UploadFile</h2>

@using (Html.BeginForm("UploadFile",
                        "Jugador",
                        FormMethod.Post,
                        new { enctype = "multipart/form-data" }))

{
    @Html.AntiForgeryToken()
    <label for="file">Cargar Archivo:</label>
    <input type="file" name="file" id="file" /><br><br>
    <input type="submit" value="Cargar Archivo" />
    <br><br>
    @ViewBag.Message
}

Laboratorio1/Laboratorio1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Inicio", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Ver Jugadores", "Index", "jugador")</li>               
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Francisco Alonzo_1197517-Angel Jiménez_1032517</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>